export const FETCH_COVID_CASES_VN = 'FETCH_COVID_CASES_VN';
export const FETCH_COVID_CASES_WORLD = 'FETCH_COVID_CASES_WORLD';
export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
